# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `dartsass-rails` gem.
# Please instead update this file by running `bin/tapioca gem dartsass-rails`.


# source://dartsass-rails//lib/dartsass-rails.rb#1
module Dartsass; end

# source://dartsass-rails//lib/dartsass/engine.rb#4
class Dartsass::Engine < ::Rails::Engine; end

# source://dartsass-rails//lib/dartsass/version.rb#2
Dartsass::VERSION = T.let(T.unsafe(nil), String)
